kind: Service
apiVersion: v1

metadata:
  name: neutron-server
  labels:
    system: openstack
    type: api
    component: neutron
  annotations:
    maia.io/scrape: "true"
spec:
  selector:
    name: neutron-server
  ports:
  - name: neutron-server
    port: {{.Values.global.neutron_api_port_internal | default 9696}}
    targetPort: neutron-api
