{{- if .Capabilities.APIVersions.Has "vcenter-operator.stable.sap.cc/v1" }}
{{- if .Values.netapp_balance_nanny.enabled }}
kind: VCenterTemplate
apiVersion: vcenter-operator.stable.sap.cc/v1
metadata:
  name: 'vcenter-datacenter-netapp-balance-secrets'
options:
  scope: 'datacenter'
  jinja2_options:
    variable_start_string: '{='
    variable_end_string: '=}'
template: |
  kind: Secret
  apiVersion: v1
  metadata:
    name: netapp-balance-nanny-{= name =}
    vcenter: {= host =}
    datacenter: {= availability_zone =}
  data:
    {{- if .Values.nannies.vcenter_username | default "" }}
    netapp_balance_vcpassword: {= "{{ .Values.nannies.vcenter_username }}" | derive_password | b64enc =}
    {{- else }}
    netapp_balance_vcpassword: {= password | b64enc =}
    {{- end }}
{{- end }}
{{- end }}
